services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pleny-restaurant-api
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    container_name: restaurant-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo:/data/db
    env_file:
      - .env

volumes:
  mongo: { }